# Generated by Django 4.2.4 on 2023-08-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_userdb_emaill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='Emaill',
            new_name='Email',
        ),
    ]
