# Generated by Django 4.2.4 on 2023-08-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_emaill_userdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Contact', models.IntegerField()),
                ('Quiry', models.CharField(max_length=500)),
            ],
        ),
    ]
